### ISSUE TITLE
I'm so in love with this plugin! But Cmd Shift L si making my code look awkward. 

### ISSUE THREAD

**Issue by lomse** [dingdong-io/brackets.beautify.io#2]
Anytime I press Cmd Shift L on a json file, the content is rearranged in a way that comma you have comma showing first before an attribute. Is there a way to prevent this? How?
Thanks. 

![screen shot 2016-09-29 at 5 06 02 pm](https://cloud.githubusercontent.com/assets/4754182/18964579/05745946-8669-11e6-940a-8f64262d3042.png)

**Comment by dingdong-io** [comment]
I'm sorry ,I copy it from[here](https://github.com/brackets-beautify/brackets-beautify),maked some change.
